baseURL = "https://daichisugiyama.com/"
title = "すぎやまだいち"
defaultContentLanguage = "ja"
languageCode = "ja-jp"
disablePathToLower = true
hasCJKLanguage = true
pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodefences = true
theme = "sugiyama"

[outputs]
    page = [ "HTML" , "AMP"  ]
    
[Params]
    profile_image = "images/profile.jpg"
#   eyecatch = "images/eyecache.jpg"
    author = "すぎやまだいち"
    author_en = "Daichi Sugiyama"
    siteurl = "daichisugiyama.com"

[taxonomies]
    tag = "tags"

[permalinks]
#    post = "/:section/:year/:month/:filename"
    post = "/:section/:year/:month/:filename"

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    extensionsmask = ["autolink"]

[menu]
#   [[menu.global_header]]
#       name = "作品集"
#       url = "/works"
#       url = "/post/2019/12/works"
#       weight = 2
    [[menu.global_header]]
        name = "ブログ"
        url = "/post"
        weight = 3
