baseURL = "https://daichisugiyama.com/"
title = "杉山大知"
defaultContentLanguage = "ja"
languageCode = "ja-jp"
disablePathToLower = true
hasCJKLanguage = true
pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodefences = true
theme = "sugiyama"

[outputs]
    page = [ "HTML" , "AMP"  ]
    
[Params]
    profile_image = "images/profile.jpg"
    eyecatch = "images/eyecache.jpg"
    author = "だいち"

[taxonomies]
    tag = "tags"

[permalinks]
    post = "/:section/:year/:month/:filename"

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    extensionsmask = ["autolink"]

[menu]
    [[menu.global_header]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.global_header]]
        name = "Works"
        url = "/works"
        weight = 2
    [[menu.global_header]]
        name = "Blog"
        url = "/blog"
        weight = 3
