baseURL = "https://daichisugiyama.com/"
languageCode = "jp"
title = "Daichi Sugiyama"
theme = "sugiyama" 

[params]
  facebook = "https://www.facebook.com/daichi.sugiyama.2012"
  #youtube = ""
  email = "daichisugiyama@outlook.com"
